# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huhu', '0002_pickmine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeperMine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine', models.IntegerField()),
            ],
        ),
    ]
